name: Docker Image CI

on:
  - pull_request

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cmpdevbuildimageruby:$(date +%s)
